import re
import json
import os
import sys

def parse_score_line(line):
    # Pattern to match: TEAM_A ScoreA - ScoreB TEAM_B Match: No ID Pool: GENDER GROUP TIME
    # Handling variations inc spacing
    # Example: CHHATTISGARH 67 - 30 UTTARAKHAND Match: No 9 Pool: WOMEN D 07:00 AM
    # Example: KARNATAKA 79- 17 TRIPURA Match: No 17 Pool: MEN F 06:30 PM
    
    # Regex Breakdown:
    # ^(.+?): Start with Team A name (non-greedy)
    # \s+(\d+): Score A
    # \s*-\s*: Hyphen with optional spaces
    # (\d+): Score B
    # \s+(.+?): Team B name (non-greedy)
    # \s+Match:\s+No\s+(\d+): Match ID
    # \s+Pool:\s+(\w+): Gender
    
    pattern = r"^(.+?)\s+(\d+)\s*-\s*(\d+)\s+(.+?)\s+Match:\s+No\s+(\d+)\s+Pool:\s+(\w+)"
    
    match = re.search(pattern, line.strip(), re.IGNORECASE)
    if match:
        t1 = match.group(1).strip().upper()
        s1 = int(match.group(2))
        s2 = int(match.group(3))
        t2 = match.group(4).strip().upper()
        mid = match.group(5).strip()
        gender = match.group(6).strip().upper()
        
        # Normalize Gender (WOMEN/MEN)
        if 'WOMEN' in gender: gender = 'WOMEN'
        elif 'MEN' in gender: gender = 'MEN'
        
        return {
            "t1": t1, "s1": s1,
            "t2": t2, "s2": s2,
            "mid": mid,
            "gender": gender
        }
    return None

def update_scores(input_file, json_file):
    if not os.path.exists(input_file):
        print(f"Input file not found: {input_file}")
        return

    # Load existing
    if os.path.exists(json_file):
        with open(json_file, "r") as f:
            try:
                data = json.load(f)
            except:
                data = {}
    else:
        data = {}
        
    updated_count = 0
    with open(input_file, "r") as f:
        for line in f:
            if not line.strip(): continue
            
            parsed = parse_score_line(line)
            if parsed:
                # Create Key: TEAM_A_VS_TEAM_B_GENDER
                # We need to ensure we match the keys generated by the app.
                # The app tries both T1_VS_T2 and T2_VS_T1.
                # So we just insert one standard key.
                
                key = f"{parsed['t1']}_VS_{parsed['t2']}_{parsed['gender']}"
                
                # Check if exists or needs update
                if key not in data or data[key]['s1'] != parsed['s1'] or data[key]['s2'] != parsed['s2']:
                    data[key] = {
                        "s1": parsed['s1'],
                        "s2": parsed['s2'],
                        "id": parsed['mid']
                    }
                    updated_count += 1
                    print(f"Updated: {key} -> {parsed['s1']}-{parsed['s2']}")
            else:
                print(f"Failed to parse: {line.strip()}")

    # Save
    with open(json_file, "w") as f:
        json.dump(data, f, indent=2)
    
    print(f"\nSuccessfully updated {updated_count} matches in {json_file}")

if __name__ == "__main__":
    # Default paths
    INPUT_TXT = "day 1 scores.txt" 
    OUTPUT_JSON = "data/processed/manual_scores.json"
    
    if len(sys.argv) > 1:
        INPUT_TXT = sys.argv[1]
        
    print(f"Parsing {INPUT_TXT}...")
    update_scores(INPUT_TXT, OUTPUT_JSON)
